group="com.github.imRoxy2222"
name="Rainbow Brackets Lite Enhance"
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
ideaVersion=2025.3
javaVersion=21
kotlinVersion=2.1.21
kotlinLanguageVersion=2.1
kotlinTargetVersion=2.1
version=0.0.2
publishChannels=Stable
kotlin.stdlib.default.dependency=false
